### ISSUE TITLE
Strange color for Italy

### ISSUE THREAD

**Issue by nrgapple** [nrgapple/historic-country-borders-app#14]
- [x] try to make colors more distinct.

based off [this issue](https://github.com/aourednik/historical-basemaps/issues/22) from @giosonego

![italy](https://user-images.githubusercontent.com/108009474/175054054-55710407-a10a-4ff0-ac99-4afd4fa7fb53.jpg)

**Comment by nrgapple** [comment]
https://github.com/nrgapple/historic-country-borders-app/commit/52e333f261c809fa6f6c0148754eab274faa4808

**Comment by aourednik** [comment]
@ngrapple : wow, this was fast :-) 

I've noticed you assing a color to each name which keeps colors identical for same countries throughout history; a great feature. Its only backdrop is taht it makes the [graph coloring](https://github.com/je-suis-tm/graph-theory/blob/master/graph%20coloring.ipynb) problem more difficult, I guess. Parhaps one could write a two-type constraint graph algorithm: 

1. nodes with relation "neighbors" must not have the same color
2. nodes with relation "same country" must have the same color

Beyond my mathematical / graph-theory skills at this point. 

But the number of different colors could be reduced if you take the `SUBJECTO` variable instead. It is now informed for every country, every year. If it is identical to `NAME`, the country is independant. If it different to name, the country is a semi-autonomous region or a colony. This would also be semantically more accurate, imo.  Using `SUBJECTO` instead of `NAME` makes the colonial history more readable:

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/7204421/175135753-df30471f-ea0e-4970-a71d-90138c9dfc71.png">

**Comment by nrgapple** [comment]
@aourednik done! https://github.com/nrgapple/historic-country-borders-app/issues/16
